import test from 'node:test';import assert from 'node:assert/strict';import worker,{__test}from'../worker/index.js';
class KV{constructor(){this.data=new Map}async get(k){return this.data.get(k)??null}async put(k,v){this.data.set(k,v)}async delete(k){this.data.delete(k)}}
const env=()=>{const ids=new KV;ids.data.set('alice',{id:'user_alice',displayName:'Alice',role:'user'});ids.data.set('bob',{id:'user_bob',displayName:'Bob',role:'user'});ids.data.set('old',{id:'user_old',displayName:'Old user',role:'user'});ids.data.set('admin',{id:'user_admin',displayName:'Admin',role:'admin'});return{PIKAMAIL_KV:new KV,TEST_IDENTITIES:ids,ASSETS:{fetch:()=>new Response('app')}}};
const call=(e,path,method='GET',data,token='alice',headers={})=>worker.fetch(new Request(`https://mail.test${path}`,{method,headers:{authorization:`Bearer ${token}`,...(data?{'content-type':'application/json'}:{}),...headers},body:data&&JSON.stringify(data)}),e);
const claim=(e,localPart,token='alice')=>call(e,'/api/address/claim','POST',{localPart,confirmPermanent:true},token);
async function setupUsers(e){await claim(e,'alicebox','alice');await claim(e,'bobbox','bob')}
test('address claiming is normalized, indexed, permanent, and available to old accounts',async()=>{const e=env();assert.equal((await claim(e,'Pika.Dev')).status,201);assert.equal(await e.PIKAMAIL_KV.get('mail-address:pika.dev'),'user_alice');assert.equal((await claim(e,'second')).status,409);assert.equal((await claim(e,'PIKA.DEV','bob')).status,409);assert.equal((await claim(e,'bad..name','bob')).status,400);assert.equal((await claim(e,'admin','bob')).status,400);assert.equal((await claim(e,'oldmail','old')).status,201);assert.equal(JSON.parse(await e.PIKAMAIL_KV.get('account:user_old')).address,'oldmail@pikamail.com')});
test('claim requires explicit permanent confirmation',async()=>{const e=env(),r=await call(e,'/api/address/claim','POST',{localPart:'alicebox',confirmPermanent:false});assert.equal(r.status,400);assert.equal((await r.json()).error,'confirmation_required')});
test('internal messages derive sender, reject external/nonexistent recipients, appear in both boxes, and mark read',async()=>{const e=env();await setupUsers(e);const bad=await call(e,'/api/mail/send','POST',{to:'person@gmail.com',subject:'x',text:'x',from:'root@pikamail.com'});assert.equal(bad.status,400);assert.equal((await call(e,'/api/mail/send','POST',{to:'nobody@pikamail.com',subject:'x',text:'x'})).status,404);const sent=await call(e,'/api/mail/send','POST',{to:'bobbox@pikamail.com',subject:'Hi',text:'Hello <script>alert(1)</script>',from:'admin@pikamail.com'});const id=(await sent.json()).messageId,stored=JSON.parse(await e.PIKAMAIL_KV.get(`message:${id}`));assert.equal(stored.from,'alicebox@pikamail.com');assert.equal((await(await call(e,'/api/mail/inbox','GET',null,'bob')).json()).messages.length,1);assert.equal((await(await call(e,'/api/mail/sent')).json()).messages.length,1);const opened=await(await call(e,`/api/mail/messages/${id}`,'GET',null,'bob')).json();assert.equal(opened.message.read,true);assert.match(opened.message.body,/<script>/);assert.equal((await call(e,`/api/mail/messages/${id}`,'GET',null,'old')).status,403)});
test('developer keys are live-only, returned once, hashed, authorized, revocable, and deliver real messages',async()=>{const e=env();await setupUsers(e);const made=await call(e,'/api/developer/apps','POST',{name:'PikApp'}),created=await made.json(),key=created.apiKey,app=created.application;assert.match(key,/^pm_live_[a-f0-9]+$/);assert.equal(JSON.parse(await e.PIKAMAIL_KV.get(`app:${app.id}`)).apiKeyHash,await __test.digest(key));assert.equal(created.application.apiKeyHash,undefined);assert.equal((await(await call(e,'/api/developer/apps')).json()).applications[0].apiKey,undefined);assert.equal((await call(e,`/api/admin/apps/${app.id}/sender`,'POST',{sender:'verify@pikamail.com'},'alice')).status,403);assert.equal((await call(e,`/api/admin/apps/${app.id}/sender`,'POST',{sender:'verify@pikamail.com'},'admin')).status,200);const send=(k,from='verify@pikamail.com')=>call(e,'/api/v1/send','POST',{from,to:'bobbox@pikamail.com',subject:'Verify',text:'482193'},'',{authorization:`Bearer ${k}`});assert.equal((await send('pm_live_bad')).status,401);assert.equal((await send(key,'security@pikamail.com')).status,403);const ok=await send(key);assert.equal(ok.status,200);const mid=(await ok.json()).messageId;assert.ok(await e.PIKAMAIL_KV.get(`message:${mid}`));assert.equal((await(await call(e,'/api/mail/inbox','GET',null,'bob')).json()).messages.length,1);await call(e,`/api/developer/apps/${app.id}/revoke`,'POST',{});assert.equal((await send(key)).status,401)});
test('disabled apps and rate limiting fail safely',async()=>{const e=env();await setupUsers(e);const d=await(await call(e,'/api/developer/apps','POST',{name:'Alerts'})).json();await call(e,`/api/admin/apps/${d.application.id}/sender`,'POST',{sender:'alerts@pikamail.com'},'admin');await call(e,`/api/admin/apps/${d.application.id}/state`,'POST',{enabled:false},'admin');const req=()=>call(e,'/api/v1/send','POST',{from:'alerts@pikamail.com',to:'bobbox@pikamail.com',subject:'x',text:'x'},'',{authorization:`Bearer ${d.apiKey}`});assert.equal((await req()).status,403);const d2=await(await call(e,'/api/developer/apps','POST',{name:'Notify'})).json();await call(e,`/api/admin/apps/${d2.application.id}/sender`,'POST',{sender:'notify@pikamail.com'},'admin');for(let i=0;i<__test.RATE_LIMIT;i++)assert.equal((await call(e,'/api/v1/send','POST',{from:'notify@pikamail.com',to:'bobbox@pikamail.com',subject:'x',text:'x'},'',{authorization:`Bearer ${d2.apiKey}`})).status,200);assert.equal((await call(e,'/api/v1/send','POST',{from:'notify@pikamail.com',to:'bobbox@pikamail.com',subject:'x',text:'x'},'',{authorization:`Bearer ${d2.apiKey}`})).status,429)});
test('tester sends real mail without exposing key and there is no sandbox route',async()=>{const e=env();await setupUsers(e);const d=await(await call(e,'/api/developer/apps','POST',{name:'Tester'})).json();await call(e,`/api/admin/apps/${d.application.id}/sender`,'POST',{sender:'testnotify@pikamail.com'},'admin');const r=await call(e,`/api/developer/apps/${d.application.id}/test`,'POST',{from:'testnotify@pikamail.com',to:'bobbox@pikamail.com',subject:'Real',text:'Delivered'});assert.equal(r.status,200);assert.equal((await call(e,'/api/v1/sandbox','POST',{})).status,404)});
test('security and route behavior: auth, admin, cursor, API and document 404',async()=>{const e=env();assert.equal((await call(e,'/api/mail/inbox','GET',null,'')).status,401);assert.equal((await call(e,'/api/admin/apps/app_abc/state','POST',{enabled:false},'alice')).status,403);assert.equal((await call(e,'/api/mail/inbox?cursor=oops')).status,400);const api=await call(e,'/api/nope');assert.equal(api.status,404);assert.match(api.headers.get('content-type'),/json/);const page=await call(e,'/nope');assert.equal(page.status,404);assert.match(page.headers.get('content-type'),/html/)});
test('frontend renders untrusted message bodies with textContent and responsive rules',async()=>{const [js,css]=await Promise.all([import('node:fs/promises').then(f=>f.readFile('public/app.js','utf8')),import('node:fs/promises').then(f=>f.readFile('public/style.css','utf8'))]);assert.match(js,/\.textContent=m\.body/);assert.doesNotMatch(js,/innerHTML=m\.body/);assert.match(css,/min-width:0/);assert.match(css,/white-space:nowrap/);assert.match(css,/@media\(max-width:767px\)/)});
