import test from 'node:test'; import assert from 'node:assert/strict'; import worker,{__test} from '../worker/index.js';
globalThis.btoa ||= s=>Buffer.from(s,'binary').toString('base64'); globalThis.atob ||= s=>Buffer.from(s,'base64').toString('binary');
class KV { constructor(){this.data=new Map()} async get(k){return this.data.get(k)??null} async put(k,v){this.data.set(k,v)} async delete(k){this.data.delete(k)} }
const setup=()=>({PIKAPP_KV:new KV(),AI:{run:async model=>({response:model.includes('guard')?'safe':'Hello from Workers AI'})},AI_MODEL:'@cf/meta/llama-3.1-8b-instruct',MODERATION_MODEL:'@cf/meta/llama-guard-3-8b',ASSETS:{fetch:()=>new Response('asset')}}); const req=(path,method='GET',body,cookie)=>new Request(`https://test${path}`,{method,headers:{...(body?{'content-type':'application/json'}:{}),...(cookie?{cookie}:{})},body:body&&JSON.stringify(body)}); const call=(env,path,method,body,cookie)=>worker.fetch(req(path,method,body,cookie),env); const session=r=>r.headers.get('set-cookie').match(/pikapp_session=([^;]+)/)[1];
async function register(env,username='alice'){return call(env,'/api/auth/register','POST',{username,email:`${username}@example.com`,displayName:username,password:'long-password-123'})}
test('passwords use Cloudflare-compatible PBKDF2 and verify stored iteration metadata',async()=>{const h=await __test.hashPassword('long-password-123');assert.match(h,/^pbkdf2-sha256\$100000\$/);assert.equal(await __test.verifyPassword('long-password-123',h),true);assert.equal(await __test.verifyPassword('wrong',h),false);const older=await __test.hashPassword('long-password-123',new Uint8Array(16),50000);assert.match(older,/^pbkdf2-sha256\$50000\$/);assert.equal(await __test.verifyPassword('long-password-123',older),true);assert.equal(await __test.verifyPassword('long-password-123',older.replace('$50000$','$100001$')),false)});
test('registration keeps email private and login authenticates',async()=>{const env=setup(),r=await register(env);assert.equal(r.status,201);const u=(await r.json()).user;assert.equal(u.email,undefined);const login=await call(env,'/api/auth/login','POST',{username:'alice',password:'long-password-123'});assert.equal(login.status,200);assert.equal((await call(env,'/api/auth/me','GET',null,`pikapp_session=${session(login)}`)).status,200)});
test('authorization, posts, moderation, likes, and deletion',async()=>{const env=setup();assert.equal((await call(env,'/api/posts','POST',{content:'hi'})).status,401);const r=await register(env),cookie=`pikapp_session=${session(r)}`;const flagged=await call(env,'/api/posts','POST',{content:'kill yourself'},cookie);assert.equal(flagged.status,422);const made=await call(env,'/api/posts','POST',{content:'hello PikApp'},cookie);assert.equal(made.status,201);const post=(await made.json()).post;assert.equal((await call(env,`/api/posts/${post.id}/like`,'POST',null,cookie)).status,200);assert.equal((await call(env,`/api/posts/${post.id}/like`,'DELETE',null,cookie)).status,200);assert.equal((await call(env,`/api/posts/${post.id}`,'DELETE',null,cookie)).status,204)});
test('follow and unfollow',async()=>{const env=setup(),a=await register(env,'alice'),ac=`pikapp_session=${session(a)}`;await register(env,'bob');assert.equal((await call(env,'/api/users/bob/follow','POST',null,ac)).status,200);assert.equal((await call(env,'/api/users/bob/follow','DELETE',null,ac)).status,200)});
test('chat and moderation use Workers AI without provider keys',async()=>{const env=setup(),calls=[];env.AI.run=async(model,input)=>{calls.push({model,input});return{response:model.includes('guard')?'unsafe S2':'Cloudflare reply'}};const r=await register(env),cookie=`pikapp_session=${session(r)}`;assert.equal((await call(env,'/api/posts','POST',{content:'provider-detected text'},cookie)).status,422);const chat=await call(env,'/api/ai/chat','POST',{messages:[{role:'user',content:'hello'}]},cookie);assert.equal(chat.status,200);assert.equal((await chat.json()).message,'Cloudflare reply');assert.deepEqual(calls.map(x=>x.model),[env.MODERATION_MODEL,env.AI_MODEL]);assert.equal('AI_API_KEY'in env,false);assert.equal('MODERATION_API_KEY'in env,false)});
test('moderator and admin permissions are backend enforced',async()=>{const env=setup(),a=await register(env,'alice'),ac=`pikapp_session=${session(a)}`,b=await register(env,'bob');const bob=(await b.json()).user;assert.equal((await call(env,'/api/mod/events','GET',null,ac)).status,403);const aliceId=await env.PIKAPP_KV.get('username:alice'),alice=JSON.parse(await env.PIKAPP_KV.get(`user:${aliceId}`));alice.role='moderator';await env.PIKAPP_KV.put(`user:${aliceId}`,JSON.stringify(alice));assert.equal((await call(env,`/api/mod/users/${bob.id}/ban`,'POST',{},ac)).status,200);assert.equal((await call(env,`/api/mod/users/${bob.id}/unban`,'POST',{},ac)).status,403);alice.role='admin';await env.PIKAPP_KV.put(`user:${aliceId}`,JSON.stringify(alice));assert.equal((await call(env,`/api/mod/users/${bob.id}/unban`,'POST',{},ac)).status,200);assert.equal((await call(env,`/api/mod/users/${bob.id}/role`,'POST',{role:'moderator'},ac)).status,200)});
