const DOMAIN = 'pikamail.com';
const RESERVED = new Set(['admin','administrator','root','support','security','abuse','postmaster','noreply','no-reply','system','api','developer','developers','pikamail','pikastudio']);
const PAGE_SIZE = 20, MAX_BODY = 20_000, RATE_LIMIT = 60;
const enc = new TextEncoder();
const json = (body, status = 200, headers = {}) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', ...headers } });
const fail = (status, error, message) => json({ ok: false, error, ...(message ? { message } : {}) }, status);
const get = async (kv, key) => { const value = await kv.get(key); return value ? JSON.parse(value) : null; };
const put = (kv, key, value, options) => kv.put(key, JSON.stringify(value), options);
const ids = prefix => `${prefix}_${[...crypto.getRandomValues(new Uint8Array(18))].map(x => x.toString(16).padStart(2,'0')).join('')}`;
const digest = async value => [...new Uint8Array(await crypto.subtle.digest('SHA-256', enc.encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('');
const local = value => String(value ?? '').trim().toLowerCase();
const validLocal = value => /^(?=.{3,32}$)[a-z0-9](?:[a-z0-9_]|\.(?!\.))*[a-z0-9]$/.test(value);
const parseAddress = value => { const text = String(value ?? '').trim().toLowerCase(); const match = /^([^@]+)@pikamail\.com$/.exec(text); return match && validLocal(match[1]) ? { local: match[1], address: text } : null; };
const body = async request => { if (Number(request.headers.get('content-length') || 0) > 25_000) return Symbol.for('large'); try { return await request.json(); } catch { return null; } };

async function identity(request, env) {
  const authorization = request.headers.get('authorization') || '';
  const cookie = request.headers.get('cookie') || '';
  if (!authorization && !cookie) return null;
  if (env.TEST_IDENTITIES) return env.TEST_IDENTITIES.get(authorization.replace(/^Bearer\s+/i, '') || cookie);
  if (!env.PIKAPP_VERIFY_URL) return null;
  const response = await fetch(env.PIKAPP_VERIFY_URL, { headers: { authorization, cookie, ...(env.PIKAPP_SERVICE_TOKEN ? { 'x-pikapp-service-token': env.PIKAPP_SERVICE_TOKEN } : {}) } });
  if (!response.ok) return null;
  const data = await response.json();
  if (!data?.verified || typeof data.user?.id !== 'string') return null;
  return { id: data.user.id, displayName: String(data.user.displayName || data.user.username || '').slice(0, 80), role: data.user.role || 'user' };
}
async function user(request, env, admin = false) { const who = await identity(request, env); if (!who) return fail(401,'unauthorized','Authentication required.'); if (admin && who.role !== 'admin') return fail(403,'forbidden','Administrator access required.'); return who; }
async function audit(env, actorId, action, target) { const event = { id: ids('audit'), actorId, action, target, createdAt: Date.now() }; await put(env.PIKAMAIL_KV, `audit:${event.id}`, event); }
async function account(env, who) { return (await get(env.PIKAMAIL_KV, `account:${who.id}`)) || { userId: who.id, displayName: who.displayName, address: null, createdAt: Date.now() }; }
async function claim(request, env) {
  const who = await user(request, env); if (who instanceof Response) return who;
  const data = await body(request); if (data === Symbol.for('large')) return fail(413,'request_too_large','Request is too large.');
  const name = local(data?.localPart);
  if (data?.confirmPermanent !== true) return fail(400,'confirmation_required','Confirm that the address is permanent.');
  if (!validLocal(name)) return fail(400,'invalid_address','Use 3–32 lowercase letters, numbers, underscores, or single dots; start and end with a letter or number.');
  if (RESERVED.has(name)) return fail(400,'reserved_address','This address is reserved.');
  const existing = await account(env, who); if (existing.address) return fail(409,'address_permanent','This account already has a permanent PikaMail address.');
  const key = `mail-address:${name}`; if (await env.PIKAMAIL_KV.get(key)) return fail(409,'address_taken','This PikaMail address is already taken.');
  await env.PIKAMAIL_KV.put(key, who.id); // Dedicated index: no account scans. KV is eventually consistent; see README.
  const owner = await env.PIKAMAIL_KV.get(key); if (owner !== who.id) return fail(409,'address_taken','This PikaMail address is already taken.');
  existing.address = `${name}@${DOMAIN}`; existing.displayName = who.displayName; await put(env.PIKAMAIL_KV, `account:${who.id}`, existing); await audit(env, who.id, 'address_claimed', existing.address);
  return json({ ok: true, account: existing }, 201);
}
async function me(request, env) { const who = await user(request, env); return who instanceof Response ? who : json({ ok:true, identity:{ id:who.id, displayName:who.displayName, role:who.role }, account:await account(env,who) }); }
const list = async (env, key) => (await get(env.PIKAMAIL_KV, key)) || [];
async function saveMessage(env, fromUserId, from, toUserId, to, subject, text, fromName = '') {
  const message = { id:ids('mail'), from, fromUserId, fromName, to, toUserId, subject, body:text, createdAt:Date.now(), read:false };
  await put(env.PIKAMAIL_KV, `message:${message.id}`, message);
  const inbox = await list(env, `inbox:${toUserId}`), sent = await list(env, `sent:${fromUserId}`);
  await Promise.all([put(env.PIKAMAIL_KV,`inbox:${toUserId}`,[message.id,...inbox].slice(0,500)), put(env.PIKAMAIL_KV,`sent:${fromUserId}`,[message.id,...sent].slice(0,500))]);
  return message;
}
function validateMail(data) { const to = parseAddress(data?.to), subject = String(data?.subject ?? '').trim(), text = String(data?.text ?? data?.body ?? ''); if (!to) return fail(400,'invalid_recipient','PikaMail currently supports internal @pikamail.com recipients only.'); if (!subject || subject.length > 200) return fail(400,'invalid_subject','Subject must contain 1–200 characters.'); if (!text || text.length > MAX_BODY) return fail(400,'invalid_message',`Message must contain 1–${MAX_BODY} characters.`); return {to,subject,text}; }
async function sendInternal(request, env) { const who=await user(request,env); if(who instanceof Response)return who; const own=await account(env,who); if(!own.address)return fail(409,'address_required','Claim a PikaMail address before sending.'); const data=await body(request); if(data===Symbol.for('large'))return fail(413,'request_too_large','Request is too large.'); const mail=validateMail(data); if(mail instanceof Response)return mail; const toUserId=await env.PIKAMAIL_KV.get(`mail-address:${mail.to.local}`); if(!toUserId)return fail(404,'recipient_not_found','Recipient not found.'); const message=await saveMessage(env,who.id,own.address,toUserId,mail.to.address,mail.subject,mail.text,own.displayName); return json({ok:true,messageId:message.id}); }
function cursor(url) { const raw=new URL(url).searchParams.get('cursor')||'0'; return /^\d{1,6}$/.test(raw)?Number(raw):null; }
async function mailbox(request,env,kind){const who=await user(request,env);if(who instanceof Response)return who;const start=cursor(request.url);if(start===null)return fail(400,'invalid_cursor','Invalid cursor.');const all=await list(env,`${kind}:${who.id}`),page=all.slice(start,start+PAGE_SIZE),messages=(await Promise.all(page.map(id=>get(env.PIKAMAIL_KV,`message:${id}`)))).filter(Boolean).map(({body,...m})=>({...m,preview:body.slice(0,120)}));return json({ok:true,messages,nextCursor:start+PAGE_SIZE<all.length?String(start+PAGE_SIZE):null});}
async function messageRoute(request,env,messageId){const who=await user(request,env);if(who instanceof Response)return who;const mail=await get(env.PIKAMAIL_KV,`message:${messageId}`);if(!mail)return fail(404,'not_found','Message not found.');if(mail.toUserId!==who.id&&mail.fromUserId!==who.id)return fail(403,'forbidden','You cannot read this message.');if(request.method==='GET'&&mail.toUserId===who.id&&!mail.read){mail.read=true;await put(env.PIKAMAIL_KV,`message:${mail.id}`,mail);}if(request.method==='PATCH'&&mail.toUserId===who.id){const data=await body(request);if(typeof data?.read!=='boolean')return fail(400,'invalid_request','read must be a boolean.');mail.read=data.read;await put(env.PIKAMAIL_KV,`message:${mail.id}`,mail);}return json({ok:true,message:mail});}
async function createApp(request,env){const who=await user(request,env);if(who instanceof Response)return who;const data=await body(request),name=String(data?.name||'').trim();if(!name||name.length>80)return fail(400,'invalid_name','Application name must contain 1–80 characters.');const key=`pm_live_${ids('').slice(1)}`,app={id:ids('app'),name,ownerUserId:who.id,senders:[],apiKeyHash:await digest(key),keySuffix:key.slice(-4),enabled:true,createdAt:Date.now()};await put(env.PIKAMAIL_KV,`app:${app.id}`,app);await put(env.PIKAMAIL_KV,`api-key:${app.apiKeyHash}`,{appId:app.id});const owned=await list(env,`apps:${who.id}`);await put(env.PIKAMAIL_KV,`apps:${who.id}`,[app.id,...owned]);await audit(env,who.id,'developer_application_created',app.id);await audit(env,who.id,'api_key_created',app.id);return json({ok:true,application:safeApp(app),apiKey:key},201);}
const safeApp=({apiKeyHash,...app})=>({...app,keyPreview:`pm_live_••••••••••••••${app.keySuffix}`});
async function apps(request,env){const who=await user(request,env);if(who instanceof Response)return who;const found=(await Promise.all((await list(env,`apps:${who.id}`)).map(id=>get(env.PIKAMAIL_KV,`app:${id}`)))).filter(Boolean).map(safeApp);return json({ok:true,applications:found});}
async function ownedApp(request,env,id){const who=await user(request,env);if(who instanceof Response)return who;const app=await get(env.PIKAMAIL_KV,`app:${id}`);return !app?fail(404,'not_found','Application not found.'):app.ownerUserId!==who.id?fail(403,'forbidden','Not your application.'):{who,app};}
async function revoke(request,env,id){const result=await ownedApp(request,env,id);if(result instanceof Response)return result;await env.PIKAMAIL_KV.delete(`api-key:${result.app.apiKeyHash}`);result.app.apiKeyHash=null;await put(env.PIKAMAIL_KV,`app:${id}`,result.app);await audit(env,result.who.id,'api_key_revoked',id);return json({ok:true});}
async function rate(env, appId){const minute=Math.floor(Date.now()/60000),key=`rate:${appId}:${minute}`,count=Number(await env.PIKAMAIL_KV.get(key)||0);if(count>=RATE_LIMIT)return false;await env.PIKAMAIL_KV.put(key,String(count+1),{expirationTtl:120});return true;}
async function apiSend(request,env){const token=(request.headers.get('authorization')||'').match(/^Bearer (pm_live_[A-Za-z0-9]+)$/)?.[1];if(!token)return fail(401,'invalid_api_key','Invalid API key.');const ref=await get(env.PIKAMAIL_KV,`api-key:${await digest(token)}`),app=ref&&await get(env.PIKAMAIL_KV,`app:${ref.appId}`);if(!app?.apiKeyHash)return fail(401,'invalid_api_key','Invalid API key.');if(!app.enabled)return fail(403,'application_disabled','Application is disabled.');const data=await body(request);if(data===Symbol.for('large'))return fail(413,'request_too_large','Request is too large.');const mail=validateMail(data);if(mail instanceof Response)return mail;const from=parseAddress(data?.from);if(!from||!app.senders.includes(from.address))return fail(403,'sender_not_authorized','You are not authorized to send from this address.');if(!await rate(env,app.id))return fail(429,'rate_limited','Too many messages. Please try again later.');const toUserId=await env.PIKAMAIL_KV.get(`mail-address:${mail.to.local}`);if(!toUserId)return fail(404,'recipient_not_found','Recipient not found.');const message=await saveMessage(env,`app:${app.id}`,from.address,toUserId,mail.to.address,mail.subject,mail.text,app.name);return json({ok:true,messageId:message.id});}
async function tester(request,env,id){const result=await ownedApp(request,env,id);if(result instanceof Response)return result;if(!result.app.enabled)return fail(403,'application_disabled','Application is disabled.');const data=await body(request),mail=validateMail(data);if(mail instanceof Response)return mail;const from=parseAddress(data?.from);if(!from||!result.app.senders.includes(from.address))return fail(403,'sender_not_authorized','You are not authorized to send from this address.');if(!await rate(env,result.app.id))return fail(429,'rate_limited','Too many messages. Please try again later.');const recipient=await env.PIKAMAIL_KV.get(`mail-address:${mail.to.local}`);if(!recipient)return fail(404,'recipient_not_found','Recipient not found.');const message=await saveMessage(env,`app:${result.app.id}`,from.address,recipient,mail.to.address,mail.subject,mail.text,result.app.name);return json({ok:true,messageId:message.id});}
async function adminAssign(request,env,id){const who=await user(request,env,true);if(who instanceof Response)return who;const app=await get(env.PIKAMAIL_KV,`app:${id}`);if(!app)return fail(404,'not_found','Application not found.');const data=await body(request),sender=parseAddress(data?.sender);if(!sender)return fail(400,'invalid_sender','A valid @pikamail.com sender is required.');const owner=await env.PIKAMAIL_KV.get(`developer-sender:${sender.local}`);if(owner&&owner!==id)return fail(409,'sender_taken','Sender is already assigned.');await env.PIKAMAIL_KV.put(`developer-sender:${sender.local}`,id);app.senders=[...new Set([...app.senders,sender.address])];await put(env.PIKAMAIL_KV,`app:${id}`,app);await audit(env,who.id,'sender_address_assigned',`${id}:${sender.address}`);return json({ok:true,application:safeApp(app)});}
async function adminState(request,env,id){const who=await user(request,env,true);if(who instanceof Response)return who;const app=await get(env.PIKAMAIL_KV,`app:${id}`);if(!app)return fail(404,'not_found','Application not found.');const data=await body(request);if(typeof data?.enabled!=='boolean')return fail(400,'invalid_request','enabled must be a boolean.');app.enabled=data.enabled;await put(env.PIKAMAIL_KV,`app:${id}`,app);await audit(env,who.id,app.enabled?'application_enabled':'application_disabled',id);return json({ok:true,application:safeApp(app)});}
const notFoundPage=()=>new Response('<!doctype html><html><meta name="robots" content="noindex"><title>Not found · PikaMail</title><style>body{font:16px system-ui;background:#f5f3ff;color:#241b45;display:grid;place-items:center;min-height:90vh}main{padding:3rem;text-align:center}a{color:#6545d8}</style><main><h1>Message not found</h1><p>This PikaMail page does not exist.</p><a href="/">Return to PikaMail</a></main></html>',{status:404,headers:{'content-type':'text/html; charset=utf-8'}});
async function route(request,env){const url=new URL(request.url),p=url.pathname,m=request.method;if(p==='/api/me'&&m==='GET')return me(request,env);if(p==='/api/address/claim'&&m==='POST')return claim(request,env);if(p==='/api/mail/send'&&m==='POST')return sendInternal(request,env);if(p==='/api/mail/inbox'&&m==='GET')return mailbox(request,env,'inbox');if(p==='/api/mail/sent'&&m==='GET')return mailbox(request,env,'sent');let x=p.match(/^\/api\/mail\/messages\/(mail_[a-f0-9]+)$/);if(x&&['GET','PATCH'].includes(m))return messageRoute(request,env,x[1]);if(p==='/api/developer/apps'&&m==='GET')return apps(request,env);if(p==='/api/developer/apps'&&m==='POST')return createApp(request,env);x=p.match(/^\/api\/developer\/apps\/(app_[a-f0-9]+)\/(revoke|test)$/);if(x&&m==='POST')return x[2]==='revoke'?revoke(request,env,x[1]):tester(request,env,x[1]);x=p.match(/^\/api\/admin\/apps\/(app_[a-f0-9]+)\/(sender|state)$/);if(x&&m==='POST')return x[2]==='sender'?adminAssign(request,env,x[1]):adminState(request,env,x[1]);if(p==='/api/v1/send'&&m==='POST')return apiSend(request,env);if(p.startsWith('/api/'))return fail(404,'not_found');if(p==='/'||p==='/docs')return env.ASSETS.fetch(request);return notFoundPage();}
export default {fetch(request,env){return route(request,env).catch(()=>fail(500,'internal_error','Internal error.'));}};
export const __test={RESERVED,validLocal,parseAddress,digest,RATE_LIMIT};
